version: '3.8'

services:
 
  tika:
    image: apache/tika:latest-full
    container_name: tika-server
    ports:
      - "9998:9998"  # external:internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  chat-app:
    image: saransh76/chat-app:latest
    container_name: chat-app
    ports:
      - "8081:8081"
    environment:
      - .env
    depends_on:
      - ollama

volumes:
  ollama_data:

